// <auto-generated />
using System;
using FlightSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228142356_AirportCode")]
    partial class AirportCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightSystem.Models.AdditionalBaggage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalBaggages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 20m,
                            Type = "Extra 10kg Baggage"
                        },
                        new
                        {
                            Id = 2,
                            Price = 35m,
                            Type = "Extra 20kg Baggage"
                        },
                        new
                        {
                            Id = 3,
                            Price = 55m,
                            Type = "Extra 30kg Baggage"
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("YearManufacturer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 160,
                            Manufacturer = "Boeing",
                            Model = "Boeing 737",
                            RegistrationNumber = "TKA123",
                            Status = true,
                            YearManufacturer = 2012
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 180,
                            Manufacturer = "Airbus",
                            Model = "Airbus A320",
                            RegistrationNumber = "LHF456",
                            Status = true,
                            YearManufacturer = 2016
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 220,
                            Manufacturer = "Airbus",
                            Model = "Airbus A321",
                            RegistrationNumber = "CAF789",
                            Status = true,
                            YearManufacturer = 2018
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoURL = "https://www.aeromobile.net/wp-content/uploads/2023/03/TurkishAirlines_logo.jpg",
                            Name = "Turkish Airlines"
                        },
                        new
                        {
                            Id = 2,
                            LogoURL = "https://cdn.freebiesupply.com/logos/large/2x/lufthansa-2-logo-png-transparent.png",
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 3,
                            LogoURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Croatia_Airlines_Logo_2.svg/744px-Croatia_Airlines_Logo_2.svg.png",
                            Name = "Croatia Airlines"
                        },
                        new
                        {
                            Id = 4,
                            LogoURL = "https://images.seeklogo.com/logo-png/46/2/air-france-logo-png_seeklogo-464865.png",
                            Name = "Air France"
                        },
                        new
                        {
                            Id = 5,
                            LogoURL = "https://logos-world.net/wp-content/uploads/2023/06/Pegasus-Airlines-Logo.png",
                            Name = "Pegasus Airlines"
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Code = "",
                            IsActive = true,
                            Name = "Sarajevo International Airport (SJJ)"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Code = "",
                            IsActive = true,
                            Name = "Mostar Airport (OMO)"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Code = "",
                            IsActive = true,
                            Name = "Franjo Tuđman Airport Zagreb (ZAG)"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Code = "",
                            IsActive = true,
                            Name = "Split Airport (SPU)"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Code = "",
                            IsActive = true,
                            Name = "Istanbul Airport (IST)"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Code = "",
                            IsActive = true,
                            Name = "Antalya Airport (AYT)"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Code = "",
                            IsActive = true,
                            Name = "Rome Fiumicino Airport (FCO)"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            Code = "",
                            IsActive = true,
                            Name = "Milan Malpensa Airport (MXP)"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 9,
                            Code = "",
                            IsActive = true,
                            Name = "Madrid Barajas Airport (MAD)"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 10,
                            Code = "",
                            IsActive = true,
                            Name = "Barcelona El Prat Airport (BCN)"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            Code = "",
                            IsActive = true,
                            Name = "Charles de Gaulle Airport (CDG)"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 12,
                            Code = "",
                            IsActive = true,
                            Name = "Nice Côte d’Azur Airport (NCE)"
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Zagreb"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Split"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            Name = "Milan"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 5,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 5,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 6,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 6,
                            Name = "Nice"
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 6,
                            Name = "France"
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromAirportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ToAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromAirportId");

                    b.HasIndex("ToAirportId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromAirportId = 1,
                            IsActive = true,
                            ToAirportId = 3
                        },
                        new
                        {
                            Id = 2,
                            FromAirportId = 1,
                            IsActive = true,
                            ToAirportId = 11
                        },
                        new
                        {
                            Id = 3,
                            FromAirportId = 3,
                            IsActive = true,
                            ToAirportId = 7
                        },
                        new
                        {
                            Id = 4,
                            FromAirportId = 5,
                            IsActive = true,
                            ToAirportId = 1
                        },
                        new
                        {
                            Id = 5,
                            FromAirportId = 7,
                            IsActive = true,
                            ToAirportId = 10
                        },
                        new
                        {
                            Id = 6,
                            FromAirportId = 10,
                            IsActive = true,
                            ToAirportId = 11
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftId = 2,
                            AirlineId = 3,
                            ArrivalTime = new DateTime(2025, 12, 30, 16, 23, 56, 290, DateTimeKind.Local).AddTicks(1666),
                            AvailableSeats = 100,
                            Code = "FS-101",
                            DepartureTime = new DateTime(2025, 12, 30, 15, 23, 56, 290, DateTimeKind.Local).AddTicks(1596),
                            DestinationId = 1,
                            Price = 120m,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AircraftId = 1,
                            AirlineId = 4,
                            ArrivalTime = new DateTime(2026, 1, 1, 17, 23, 56, 290, DateTimeKind.Local).AddTicks(1682),
                            AvailableSeats = 140,
                            Code = "FS-202",
                            DepartureTime = new DateTime(2026, 1, 1, 15, 23, 56, 290, DateTimeKind.Local).AddTicks(1679),
                            DestinationId = 2,
                            Price = 180m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FlightSystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdditionalBaggageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalBaggageId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalBaggageId = 1,
                            CreatedAt = new DateTime(2025, 12, 28, 14, 23, 56, 290, DateTimeKind.Utc).AddTicks(1968),
                            FlightId = 1,
                            SeatNumber = "12A",
                            Status = 0,
                            TotalPrice = 140m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mail.com",
                            FirstName = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = "Hash",
                            PasswordSalt = "Salt",
                            PhoneNumber = "000000000",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FlightSystem.Models.Airport", b =>
                {
                    b.HasOne("FlightSystem.Models.City", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("FlightSystem.Models.City", b =>
                {
                    b.HasOne("FlightSystem.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FlightSystem.Models.Destination", b =>
                {
                    b.HasOne("FlightSystem.Models.Airport", "FromAirport")
                        .WithMany()
                        .HasForeignKey("FromAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightSystem.Models.Airport", "ToAirport")
                        .WithMany()
                        .HasForeignKey("ToAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromAirport");

                    b.Navigation("ToAirport");
                });

            modelBuilder.Entity("FlightSystem.Models.Flight", b =>
                {
                    b.HasOne("FlightSystem.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightSystem.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightSystem.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("FlightSystem.Models.Notification", b =>
                {
                    b.HasOne("FlightSystem.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightSystem.Models.Reservation", b =>
                {
                    b.HasOne("FlightSystem.Models.AdditionalBaggage", "AdditionalBaggage")
                        .WithMany()
                        .HasForeignKey("AdditionalBaggageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlightSystem.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightSystem.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdditionalBaggage");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightSystem.Models.Aircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightSystem.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightSystem.Models.City", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("FlightSystem.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("FlightSystem.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
